###
@userId = {{ createUser.response.body.id}}

@postId = {{ createPost.response.body.id}}


###
# @name createUser
POST http://localhost:8080/users
Content-Type: application/json

{
  "name": "John Doe",
  "age": 30
}

###
GET http://localhost:8080/users


###
GET http://localhost:8080/users/{{userId}}


###
PUT http://localhost:8080/users/{{userId}}
Content-Type: application/json

{
  "name": "Ze Jose",
  "age": 30
}

###
DELETE http://localhost:8080/users/{{userId}}



###
# @name createPost
POST http://localhost:8080/users/{{userId}}/posts
Content-Type: application/json

{
  "post_text": "Hello World"
}

###
GET http://localhost:8080/users/{{userId}}/posts