version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_quarkus
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: juancassiano
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: quarkus_db
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_quarkus
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: juancassiano@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data: